import assert from 'node:assert/strict';
import {Fight} from './dist/combat.js';
import {Scene} from './dist/scene.js';
import {mat} from './dist/engine.js';
const make=()=>{const f=new Fight(()=>{},()=>.9);f.start();f.phase='fight';f.cpu.aiDelay=999;f.p.x=0;f.cpu.x=1.5;return f;};
const run=(f,n,input={})=>{for(let i=0;i<n;i++)f.tick(1/120,input);};
let f=make();assert(f.attack(f.p,'punch'));run(f,100);assert.equal(f.cpu.hp,92);assert.equal(f.p.hp,100);
f=make();f.cpu.ai.guard=true;f.attack(f.p,'punch');run(f,100);assert.equal(f.cpu.hp,99);
f=make();f.cpu.x=4;f.attack(f.p,'punch');run(f,100);assert.equal(f.cpu.hp,100);
f=make();f.p.yaw=Math.PI;f.attack(f.p,'punch');run(f,100);assert.equal(f.cpu.hp,100);
f=make();assert.equal(f.attack(f.p,'special'),false);assert.equal(f.p.energy,50);f.p.energy=100;f.cpu.ai.guard=true;assert(f.attack(f.p,'special'));assert.equal(f.p.energy,0);run(f,180);assert(f.cpu.hp<80,'Special connects repeatedly through guard');
f=make();f.p.style='wing';f.p.energy=100;f.attack(f.p,'special');run(f,180);assert.equal(f.cpu.hp,60,'Wing Chun signature hits five times');
f=make();f.cpu.hp=4;f.attack(f.p,'punch');run(f,40);assert.equal(f.phase,'roundend');assert.equal(f.p.wins,1);run(f,440);assert.equal(f.round,2);assert.equal(f.p.hp,100);assert.equal(f.cpu.hp,100);
f=make();f.p.x=-6.54;run(f,4,{x:-1});assert.equal(f.phase,'roundend');assert.equal(f.cpu.wins,1);
f=make();f.clock=.01;f.p.hp=90;run(f,4);assert.equal(f.cpu.wins,1);
f=make();f.paused=true;run(f,100,{x:1});assert.equal(f.clock,60);assert.equal(f.p.x,0);
f=make();f.p.wins=1;f.cpu.hp=1;f.attack(f.p,'kick');run(f,600);assert.equal(f.phase,'matchend');assert.equal(f.p.wins,2);
let hits=0;f=new Fight(e=>{if(e.type==='hit')hits++;},()=>.71);f.start();run(f,1500);assert(hits>0,'CPU autonomously approaches and attacks');
let meshes=0;const finite=x=>{assert(x.every(Number.isFinite));};const renderer={aspect:1.78,begin(eye,target){finite(eye);finite(target);},mesh(type,m,c){finite(m);finite(c);meshes++;},draw(type,p,s,c,r,parent){finite(p);finite(s);if(r)finite(r);if(parent)finite(parent);meshes++;},bone(a,b,rad,c,parent){finite(a);finite(b);finite(parent);meshes++;}};
const scene=new Scene(renderer);f=make();for(const style of['drunk','wing']){f.p.style=style;for(const type of['punch','kick','special']){f.p.action=null;f.p.energy=100;f.attack(f.p,type);for(let i=0;i<100;i++){f.tick(.008,{});scene.render(f,.008);}}}assert(meshes>10000);
assert.equal(mat.mul(mat.translate(1,2,3),mat.scale(2,3,4))[12],1);
console.log('PASS: single hits, guard, distance/facing, both signatures, round reset, ring out, timeout, pause, match result, CPU, finite scene transforms.');
console.log('Scene objects:',scene.static.length,'; exercised draw calls:',meshes);
